[2021-06-08 20:18:22,635] cloud50/WARNING/locust.main: System open file limit '1024' is below minimum setting '10000'. It's not high enough for load testing, and the OS didn't allow locust to increase it by itself. See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
[2021-06-08 20:18:22,636] cloud50/INFO/locust.main: Starting Locust 1.5.3
[2021-06-08 20:18:23,530] cloud50/INFO/locust.runners: Spawning 6 users at the rate 0.125 users/s (0 users already running)...
[2021-06-08 20:19:03,540] cloud50/INFO/locust.runners: All users spawned: SimulateUserBenchmark: 6 (6 total running)
[2021-06-08 20:19:25,966] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:20:15,267] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:21:17,655] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:22:20,628] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:22:20,629] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:22:51,978] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:24:34,269] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:24:50,755] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:26:11,619] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:26:53,865] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:27:30,272] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:27:48,480] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:29:08,820] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:31:52,582] cloud50/ERROR/locust.user.task: Cannot choose from an empty sequence
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 290, in run
    self.execute_next_task()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File "/usr/local/lib/python3.8/dist-packages/locust/user/task.py", line 428, in execute_task
    task(self.user)
  File "/home/gsd/benchmark/wiki/locustfiles/simulateUser.py", line 37, in readPage
    actions.loadPage(self, random.choice(pages)["path"])
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

[2021-06-08 20:33:23,532] cloud50/INFO/locust.runners: Stopping 6 users
[2021-06-08 20:33:23,533] cloud50/INFO/locust.runners: 6 Users have been stopped, 0 still running
[2021-06-08 20:33:23,533] cloud50/INFO/locust.runners: Got quit message from master, shutting down...
[2021-06-08 20:33:23,534] cloud50/INFO/locust.main: Running teardowns...
[2021-06-08 20:33:23,534] cloud50/INFO/locust.main: Shutting down (exit code 0), bye.
[2021-06-08 20:33:23,534] cloud50/INFO/locust.main: Cleaning up runner...
