[2021-05-31 16:22:51,966] cloud50/WARNING/locust.main: System open file limit '1024' is below minimum setting '10000'. It's not high enough for load testing, and the OS didn't allow locust to increase it by itself. See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
[2021-05-31 16:22:51,967] cloud50/INFO/locust.main: Starting Locust 1.5.3
[2021-05-31 16:22:53,010] cloud50/INFO/locust.runners: Spawning 7 users at the rate 0.5 users/s (0 users already running)...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 166, in run_user
    user.run()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 132, in run
    self.on_start()
  File "/home/gsd/benchmark/peertube/locustfiles/mixed.py", line 65, in on_start
    self.token = resptoken.json()['access_token']
KeyError: 'access_token'
2021-05-31T15:22:53Z <Greenlet at 0x7f00b129f7b0: run_user(<mixed.QuickstartUser object at 0x7f00b11f9280>)> failed with KeyError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 166, in run_user
    user.run()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 132, in run
    self.on_start()
  File "/home/gsd/benchmark/peertube/locustfiles/mixed.py", line 65, in on_start
    self.token = resptoken.json()['access_token']
KeyError: 'access_token'
2021-05-31T15:22:55Z <Greenlet at 0x7f00b129f8c0: run_user(<mixed.QuickstartUser object at 0x7f00af774f40>)> failed with KeyError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 166, in run_user
    user.run()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 132, in run
    self.on_start()
  File "/home/gsd/benchmark/peertube/locustfiles/mixed.py", line 65, in on_start
    self.token = resptoken.json()['access_token']
KeyError: 'access_token'
2021-05-31T15:22:57Z <Greenlet at 0x7f00b129fae0: run_user(<mixed.QuickstartUser object at 0x7f00aeee3f70>)> failed with KeyError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 166, in run_user
    user.run()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 132, in run
    self.on_start()
  File "/home/gsd/benchmark/peertube/locustfiles/mixed.py", line 65, in on_start
    self.token = resptoken.json()['access_token']
KeyError: 'access_token'
2021-05-31T15:22:59Z <Greenlet at 0x7f00b129fe10: run_user(<mixed.QuickstartUser object at 0x7f00aeee3e80>)> failed with KeyError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 166, in run_user
    user.run()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 132, in run
    self.on_start()
  File "/home/gsd/benchmark/peertube/locustfiles/mixed.py", line 65, in on_start
    self.token = resptoken.json()['access_token']
KeyError: 'access_token'
2021-05-31T15:23:01Z <Greenlet at 0x7f00aef08040: run_user(<mixed.QuickstartUser object at 0x7f00aeefadf0>)> failed with KeyError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 166, in run_user
    user.run()
  File "/usr/local/lib/python3.8/dist-packages/locust/user/users.py", line 132, in run
    self.on_start()
  File "/home/gsd/benchmark/peertube/locustfiles/mixed.py", line 65, in on_start
    self.token = resptoken.json()['access_token']
KeyError: 'access_token'
2021-05-31T15:23:03Z <Greenlet at 0x7f00b129fe10: run_user(<mixed.QuickstartUser object at 0x7f00aeefaeb0>)> failed with KeyError

[2021-05-31 16:23:05,016] cloud50/INFO/locust.runners: All users spawned: QuickstartUser: 7 (1 total running)
