Count,Message,Traceback,Nodes
18,Cannot choose from an empty sequence,"  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 290, in run
    self.execute_next_task()
  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 428, in execute_task
    task(self.user)
  File ""/home/gsd/benchmark/wiki/locustfiles/simulateUser.py"", line 37, in readPage
    actions.loadPage(self, random.choice(pages)[""path""])
  File ""/usr/lib/python3.8/random.py"", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
","c, l, o, u, d, 6, 9, _, e, 8, d, 4, 5, 4, 4, 6, f, 7, a, d, 4, 8, e, f, 8, d, 6, 5, d, 7, 9, 0, e, a, 9, 6, 6, 1, 2, 3, ,,  , c, l, o, u, d, 6, 9, _, 2, a, d, f, 9, 8, 5, 3, 1, 3, 2, 6, 4, 4, e, d, 8, e, f, c, 8, 3, 6, 2, b, a, 9, d, d, 7, 4, 5"
11,Cannot choose from an empty sequence,"  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 290, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 428, in execute_task
    task(self.user)
  File ""/home/gsd/benchmark/wiki/locustfiles/simulateUser.py"", line 37, in readPage
    actions.loadPage(self, random.choice(pages)[""path""])
  File ""/usr/lib/python3.8/random.py"", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
","c, l, o, u, d, 5, 0, _, 3, 2, f, f, f, 3, 1, 9, a, 6, 1, 7, 4, c, 8, 3, a, c, d, a, d, 2, f, f, 6, 5, 9, 0, f, b, 2, b, ,,  , c, l, o, u, d, 5, 0, _, c, b, f, 1, a, 6, 4, 3, d, 3, c, f, 4, c, 5, 9, 9, f, f, d, 3, 2, e, 2, f, f, 7, 2, 9, b, 2, 1"
